### ISSUE TITLE
ghc 9 - Couldn't match MonadCatch with MonadThrow

### ISSUE THREAD

**Issue by funketh** [polysemy-research/polysemy-zoo#69]
MonadCatch hasn't been touched since 2019 so this probably has something to do with ghc 9 changes.
```hs
[ 3 of 31] Compiling Polysemy.ConstraintAbsorber.MonadCatch
                            
/home/theo/prj/polysemy-zoo/src/Polysemy/ConstraintAbsorber/MonadCatch.hs:83:20: error:
    * Couldn't match type: C.MonadCatch (Sem r)
                     with: C.MonadThrow (Sem r)
      Expected: (C.MonadThrow (Sem r) => Sem r a) -> Sem r a
        Actual: (C.MonadCatch (Sem r) => Sem r a) -> Sem r a
    * In the expression: absorbMonadCatch
      In an equation for `absorbMonadThrow':
          absorbMonadThrow = absorbMonadCatch
    * Relevant bindings include
        absorbMonadThrow :: (C.MonadThrow (Sem r) => Sem r a) -> Sem r a
          (bound at src/Polysemy/ConstraintAbsorber/MonadCatch.hs:83:1)
   |                        
83 | absorbMonadThrow = absorbMonadCatch
   |                    ^^^^^^^^^^^^^^^^
```
The `stack.yaml` I used:
```yml
compiler: ghc-9.0.1
resolver: nightly-2020-05-07

allow-newer: true

packages:
- .

extra-deps:
- atomic-primops-0.8.4
- compact-0.2.0.0
- random-1.2.0
- splitmix-0.1.0.3
- syb-0.7.2.1
- th-abstraction-0.4.2.0
- QuickCheck-2.14.2
# GHC 9 patch (not yet on hackage)
- github: polysemy-research/polysemy
  commit: 09c65bdae9c9ce50a55c7ee2ab9681916f09f4c3
  subdirs: [.]
```
